### ISSUE TITLE
ERROR on php formating

### ISSUE THREAD

**Issue by coscho** [akalongman/sublimetext-codeformatter#227]
Format error:
PHP Warning:  Unsupported declare 'strict_types' in phar:///home/clara/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar/fmt.stub.php on line 1
Warning: Unsupported declare 'strict_types' in phar:///home/clara/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar/fmt.stub.php on line 1
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in phar:///home/clara/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar/fmt.stub.php on line 307
Parse error: syntax error, unexpected ':', expecting ';' or '{' in phar:///home/clara/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar/fmt.stub.php on line 307

Hi Guys I am getting this error on php formatting.

HELP :+1:

**Comment by akalongman** [comment]
Fixed. Update to 3.3.2 version

**Comment by coscho** [comment]
I see latest version is 3.3.2 ... where do I get 3.3.2 ??

**Comment by akalongman** [comment]
Wait for package control update or update manually from git

**Comment by coscho** [comment]
I updated manually from git. ... the same ... :(

**Comment by akalongman** [comment]
Try now. Reinstall

**Comment by coscho** [comment]
reinstalled .. the same :(

**Comment by akalongman** [comment]
No way :) Close sublime, reinstall full package and open sublime

**Comment by maxkostinevich** [comment]
Hi there, just had the same issue, howver I've downloaded a version 3.3.2 from GitHub and updated the package manually and it works fine now.

To update package manually follow the short instruction:
1. Download a zip from GitHub (make sure you have switched to tag 3.3.2, because master branch doesn't work for me for some reason)
2. Go to **Preferences -> Browse Packages** in your sublimetext
3. Close Sublime text
4. Replace files inside of **CodeFormatter** folder to files you have downloaded from GitHub

**Comment by coscho** [comment]
Thank you @maxkostinevich  . That does the trick. Thank you @akalongman for your awesome , helpful plugin.

**Comment by jatinbphp** [comment]
Thank You @maxkostinevich .

**Comment by akalongman** [comment]
Please check version 3.5.1 and let me know if bug is fixed
