### ISSUE TITLE
format_on_save not working for codeformatter_php_options

### ISSUE THREAD

**Issue by Jaspur** [akalongman/sublimetext-codeformatter#280]
Hi,

I have this in the following file:
```/Sublime Text 3/Packages/User/Preferences.sublime-settings```
```
 "codeformatter_php_options":
    {
        "syntaxes": "php", // Syntax names which must process PHP formatter
        "php_path": "/usr/local/bin/php", 
        "format_on_save": true, 
}
```
But it's not formatting on Save.. But it does when I do it manually (CMD+Shift+P: FormatCode)

**Comment by menzow** [comment]
See this issue was opened a while ago, but I just had the same problem.

The solution is putting your configuration file here: `Packages/User/CodeFormatter.sublime-settings`.

From the ST3 UI, go to `Sublime Text > Package Settings > CodeFormatter > Settings - User`
It will open the appropriate settings file.
