### ISSUE TITLE
New phpfmt

### ISSUE THREAD

**Issue by subins2000** [akalongman/sublimetext-codeformatter#289]
I have [forked phpfmt](https://github.com/subins2000/phpfmt) to continue the development. I have added a new feature `SpaceAroundParentheses` too.

It would be great if CodeFormatter start using the new [phpfmt](https://github.com/subins2000/phpfmt/blob/master/build/phpfmt.phar).

**Comment by akalongman** [comment]
Is your fork stable? Do you have tests for new features?

**Comment by akalongman** [comment]
And also please check if this issues fixed in your fork: 
https://github.com/akalongman/sublimetext-codeformatter/issues/286
https://github.com/akalongman/sublimetext-codeformatter/issues/266
https://github.com/akalongman/sublimetext-codeformatter/issues/251
https://github.com/akalongman/sublimetext-codeformatter/issues/250
and like this

**Comment by subins2000** [comment]
It's currently stable. I'll try to fix the bugs and add new features.

I haven't written any unit tests yet. Will do that too.

**Comment by akalongman** [comment]
@subins2000 thank you

**Comment by akalongman** [comment]
I decided to move on PHP CS FIXER https://github.com/akalongman/sublimetext-codeformatter/issues/355#issuecomment-381722577
