### ISSUE TITLE
No module named 'jsbeautifier.core.acorn'

### ISSUE THREAD

**Issue by OlivierBlomme** [akalongman/sublimetext-codeformatter#404]
I have been experiencing this issue for a couple of days now. I happens when i want to format as scss or css. The other formatters are fine. Sublime Text 3 on Ubuntu 18.04.

**Comment by akalongman** [comment]
@Ampretuzo is this related with https://github.com/akalongman/sublimetext-codeformatter/pull/400 ?

**Comment by Ampretuzo** [comment]
@akalongman it is.

`jsbeautifier` package upgrade introduced module refactor - that's why import fails.
I fixed the import, but then something else fails (due to `jsbeautifier` refactor again) which might or might not be simple to fix.

I'll prepare revert PR meanwhile.

Sorry to introduce bugs in the plugin, I definitely forgot to test on css!

**Comment by akalongman** [comment]
@Ampretuzo no problem :)

**Comment by v3nt** [comment]
hello - has this been fixed at all? Still getting the error and can't format any code.

**Comment by niladam** [comment]
Sadly, i'm also affected by this.

**Comment by dompl** [comment]
Same here unfortunately. Any updates on this? Thanks

**Comment by Ampretuzo** [comment]
@v3nt , @niladam , @dompl I introduced this bug in #400 and it'll be resolved when revert #405 is merged.

**Comment by akalongman** [comment]
Merged and released as 4.3.1
